> Tensorflow Documentation - https://www.tensorflow.org/api_docs/python/

UV is An extremely fast Python package and project manager, faster 10-100x time than pip.
Installing UV, setting Up Virtual Environment and downloading depending dependencies.

```sh
pip install uv
uv venv
uv pip install -r requirements.txt
```

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Math Operations

This notebook will include all the methods of tf.math.

In [2]:
# abs - Computes the absolute value of a tensor.

x = tf.constant([-2.25,3.25])
tf.math.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [3]:
# complex number
x_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [4]:
# square root & square
tf.sqrt(tf.square(-2.25) + tf.square(4.75))

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [ ]:
# Add, Sub, Mul, Div
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.int32)
x_2 = tf.constant([7,6,2,6,7,11], dtype = tf.int32)

print(tf.add(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2)) # divide returns inf on denominator being 0

# divide_no_nan - returns 0 if denominator is 0 and it takes only arrays in float
# Similarly like Add, Sub, Mul, Div, there is pov for Power -> It also works elementwise

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [ ]:
# multiply_no_nan - Computes the product of x and y and returns 0 if the y is zero, even if x is NaN or infinite.

x = tf.constant([5.0, np.inf, np.nan])
y = tf.constant([-6.0, 0, 0])
tf.math.multiply_no_nan(x, y) #==> [-30. ,0. ,0.]

In [ ]:
# multiply_no_nan is Assymetric function
x = tf.constant([-2.0, -5.0, 0, 0])
y = tf.constant([-1.0, -6, np.inf, np.nan])
tf.math.multiply_no_nan(x, y) #==> [2. ,30. ,nan ,nan]

In [6]:
# Broadcasting

a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.constant([7, 8, 9])
d = tf.constant([10])

# print(tf.math.add(a, b, c)) # ERROR! No more than 2 variables can be paseed
print(tf.math.add_n([a, b, c])) # more than 2 variables can be passed.
print(tf.math.add(a, d)) # Works (Broadcasting): [11, 12, 13]
# print(tf.math.add_n([a, b, d])) # ERROR! Broadcasting is not allowed

tf.Tensor([12 15 18], shape=(3,), dtype=int32)
tf.Tensor([11 12 13], shape=(3,), dtype=int32)


- tf.reduce_sum(inputs, axis=0) - This is the reduction operation for tf.add_n. 
- Reduces input_tensor along the dimensions given in axis. Unless keepdims is true, the rank of the tensor is reduced by 1 for each of the entries in axis, which must be unique.
- If keepdims is true, the reduced dimensions are retained with length 1.
- If axis is None, all dimensions are reduced, and a tensor with a single element is returned.

In [7]:
x = tf.constant([
    [1, 1, 1], # Row 0
    [1, 1, 1] # Row 1
])
x.numpy() # Converts tensor array to numpy
tf.reduce_sum(x).numpy() # Calculate sum of all elements

np.int32(6)

In [8]:
# Axis = 0 -> Rows => Adding rows
tf.reduce_sum(x, 0).numpy() # same operation as add_n as reduction along 1st dimension

array([2, 2, 2], dtype=int32)

In [9]:
# Axis = 1 -> Columns
tf.reduce_sum(x, 1).numpy() # reduction along 2nd dimension : [ 1 + 1 + 1, 1 + 1 + 1 ] -> [3,3]

array([3, 3], dtype=int32)

In [10]:
# First it performs row reduction: Adding rows : [1, 1, 1] + [1, 1, 1] -> [2,2,2]
# Then it performs column reduction: Adding columns : 2 + 2 + 2 = 6

tf.reduce_sum(x, [0, 1]).numpy() # reduction along 1st & 2nd dimension 

np.int32(6)

In [ ]:
# argmax - Returns the index with the largest value across axes of a tensor.
# Same working for argmin for index with smallest value across axes of a tensor.
A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmax(A)
# Returns first index in case smallest value is duplicate

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [12]:
B = tf.constant([
    [2, 20, 30, 3, 6], # Row 0
    [3, 11, 16, 1, 8], # Row 1
    [14, 45, 23, 5, 27] # Row 2
])
tf.math.argmax(B, 0) # Operation around Row so we take maximum index out of elements of 1 column
# [2, 2, 0, 2, 2] for values [14,45,30,5,27]

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [13]:
tf.math.argmax(B, 1) # Operation around column
# [ 2, 2, 1] for [30,16,45]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>

In [17]:
# maximum - Returns the max of x and y (i.e. x > y ? x : y) element-wise.
# Same for minimum
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [ ]:
# maximum - broadcasting
x = tf.constant([-5., 0., 1., -4.])
y = tf.constant([-3.])


tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  1., -3.], dtype=float32)>

Comparisions Method Names
- equal
- not_equal
- greater
- greater_equal
- less
- less_equal

```py
tf.math.name(Tensor1, Tensor2) # Returns Element-wise Boolean Result
```

Trigonometric Functions
- **sin(x)** | For x ∈ (-∞, ∞), sin(x) ∈ [-1, 1]
- **cos(x)** | For x ∈ (-∞, ∞), cos(x) ∈ [-1, 1]
- **tan(x)** = sin(x)/cos(x) | For x ∈ (-∞, ∞), x ≠ (2k+1)π/2, tan(x) ∈ (-∞, ∞)
- **asin(x)** | For x ∈ [-1, 1], asin(x) ∈ [-π/2, π/2]
- **acos(x)** | For x ∈ [-1, 1], acos(x) ∈ [0, π]
- **atan(x)** | For x ∈ (-∞, ∞), atan(x) ∈ (-π/2, π/2)

Hyperbolic Functions
- **sinh(x)** = (exp(x) - exp(-x))/2 | For x ∈ (-∞, ∞), sinh(x) ∈ (-∞, ∞)
- **cosh(x)** = (exp(x) + exp(-x))/2 | For x ∈ (-∞, ∞), cosh(x) ∈ [1, ∞)
- **tanh(x)** = (exp(x) - exp(-x)) / (exp(x) + exp(-x)) | For x ∈ (-∞, ∞), tanh(x) ∈ (-1, 1)
- **asinh(x)** = ln(x + √(x² + 1)) | For x ∈ (-∞, ∞), asinh(x) ∈ (-∞, ∞)
- **acosh(x)** = ln(x + √(x² - 1)) | For x ∈ [1, ∞), acosh(x) ∈ [0, ∞)
- **atanh(x)** = 0.5 * ln((1+x)/(1-x)) | For x ∈ (-1, 1), atanh(x) ∈ (-∞, ∞)

Common Deep Learning Activations
- **sigmoid(x)** = 1 / (1 + exp(-x)) | For x ∈ (-∞, ∞), sigmoid(x) ∈ (0, 1)
- **relu(x)** = max(0, x) | For x ∈ (-∞, ∞), relu(x) ∈ [0, ∞)
- **softplus(x)** = ln(1 + exp(x)) | For x ∈ (-∞, ∞), softplus(x) ∈ (0, ∞)

```py
tf.math.name(Tensor) # Returns Element-wise Result
```

In [26]:
# top_k - Finds values & indices of the k largest entries for the last dimension.
tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1], k=3)

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9], dtype=int32)>)

in_top_k

- Outputs whether the targets are in the top K predictions.
- If the target is (0), see first row and column at index (0), if it belongs to the top 2 values, it will return true otherwise false
- Then target is 1 for 2nd row, if element at [1,1] belongs to top 2 values, it will return true otherwise false and so on...

In [29]:
target = tf.constant([0, 1, 3])
pred = tf.constant([
 [1.2, -0.3, 2.8, 5.2],
 [0.1, 0.0, 0.0, 0.0],
 [0.0, 0.5, 0.3, 0.3]] )
tf.math.in_top_k(target, pred, 2)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True,  True])>