> Tensorflow Documentation - https://www.tensorflow.org/api_docs/python/

UV is An extremely fast Python package and project manager, faster 10-100x time than pip.
Installing UV, setting Up Virtual Environment and downloading depending dependencies.

```sh
pip install uv
uv venv
uv pip install -r requirements.txt
```

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

# Types of Tensors

This notebook focuses particularly on these types of tensors:-
- Ragged Tensors
- Sparse Tensors
- String Tensors

In [3]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
tensor_two_d.shape

TensorShape([4, 3])

In [4]:
# Ragged Tensor - Without it, you can't keep your column values flexible, it will show error.

tensor_two_d =[[1,2,0],
                [3,],
                [1,5,6,5,6],
                [2,3]]

print(tf.ragged.constant(tensor_two_d).shape) # None as it is not fixed
tf.ragged.constant(tensor_two_d)

(4, None)


<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>

In [5]:
# tf.ragged.boolean_mask - Applies a boolean mask to data without flattening the mask dimensions.

# Aliases for True & False so data and mask line up.
T, F = (True, False)

tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]
).to_list()

[[1, 3], [], [7]]

In [6]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[F, F, T], [F], [T, T]])
).to_list()

[[3], [], [5, 6]]

In [7]:
tf.ragged.boolean_mask(  # Mask rows of a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([True, False, True])
).to_list()

[[1, 2, 3], [5, 6]]

Whole documentation on ragged tensor - https://www.tensorflow.org/api_docs/python/tf/RaggedTensor

In [ ]:
# from_row_lengths - Creates a RaggedTensor with rows partitioned by row_lengths.
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0])
)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
# from_row_limits - Creates a RaggedTensor with rows partitioned by row_limits.
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8])
)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
# from_row_splits - Creates a RaggedTensor with rows partitioned by row_splits.

print(tf.RaggedTensor.from_row_splits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_splits=[0, 4, 4, 7, 8, 8]) # splits: 0 to 4, 4 to 4, 4 to 7, 7 to 8, 8 to 8
)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [14]:
# tf.sparse.SparseTensor - Represents a sparse tensor.

t = tf.sparse.SparseTensor(indices=[[1, 1], [3, 4]], values=[11, 56], dense_shape=[5, 6])
print(t)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [15]:
tf.sparse.to_dense(t)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [ ]:
# String Tensor
s = tf.constant(["Hello", "I am", "a string"])
print(s)

tf.Tensor([b'Hello' b'I am' b'a string'], shape=(3,), dtype=string)


In [ ]:
# join
tf.strings.join(s, separator =" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello I am a string'>

In [19]:
# tf.strings.length - String lengths of input.
strings = tf.constant(['Hello','TensorFlow', '\U0001F642'])
tf.strings.length(strings).numpy() # default counts bytes

tf.strings.length(strings, unit="UTF8_CHAR").numpy()

array([ 5, 10,  1], dtype=int32)

In [20]:
# tf.strings.lower - Converts all uppercase characters into their respective lowercase replacements.
tf.strings.lower("CamelCase string and ALL CAPS")

<tf.Tensor: shape=(), dtype=string, numpy=b'camelcase string and all caps'>